{% set name = "dolo" %}
{% set version = "0.4.9.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e032a0697f7f9b0dea350931e881bf43dc6e03876e2338cd6d806cfee9a9196c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip ==20.0.2
    - python >=3.7
    - poetry
  run:
    - dolang >=0.0.8
    - interpolation >=2.1.6
    - ipython >=7.12.0
    - matplotlib-base >=3.0
    - multipledispatch >=0.6.0
    - numpy >=1.18.1
    - pandas >=1.0.1
    - python >=3.7
    - pyyaml >=5.3
    - quantecon >=0.4
    - ruamel.yaml >=0.16.10
    - scipy >=1.4.1
    - xarray >=0.15.0

test:
  imports:
    - dolang
    - dolang.tests

about:
  home: https://github.com/EconForge/dolo.py
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Dolo Modeling Language

extra:
  recipe-maintainers:
    - albop
