{% set name = "dolo" %}
{% set version = "0.4.9.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9c41bc96fa31629289a0fcc0083be0df3076cae8bf9aee634f8d0006125b4d2
  patches:
    - support-modern-python.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.8
  run:
    - python >={{ python_min }},<3.14
    - dolang >=0.0.20,<0.0.22
    - interpolation >=2.2.7,<3
    - ipython >=7.12.0
    - matplotlib-base >=3.6,<4
    - multipledispatch >=0.6,<0.7
    - sympy >=1.10.1
    - numba >=0.59.1
    - numpy >=1.23.1
    - pandas >=1.5,<3
    - pyyaml >=6,<7
    - quantecon >=0.7.2,<1
    - scipy >=1.10,<2
    - xarray >=2022.6

test:
  imports:
    - dolo
    - dolo.algos.fb
    - dolo.numeric.processes
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/EconForge/dolo.py
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Dolo Modeling Language

extra:
  recipe-maintainers:
    - albop
    - anutosh491
