{% set name = "dolo" %}
{% set version = "0.4.9.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3778634e616e014635915a06876e97e699a730fa98646eba0ef478a3eb7bc109

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  patches:
    - fix_poetry.patch

requirements:
  host:
    - pip ==22.2.2
    - python >=3.8,<3.11
    - poetry
  run:
    - dolang ==0.0.18
    - interpolation >=2.1.8
    - ipython >=7.12.0
    - matplotlib-base >=3.0
    - multipledispatch >=0.6.0
    - numpy >=1.22.2
    - pandas >=1.4.2
    - python >=3.8
    - pyyaml >=5.3
    - quantecon >=0.5.3
    - scipy >=1.9.1
    - xarray >=0.15.0

test:
  imports:
    - dolang
    - dolang.tests

about:
  home: https://github.com/EconForge/dolo.py
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Dolo Modeling Language

extra:
  recipe-maintainers:
    - albop
